controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite = sprites.create(img`
        ........................
        ........................
        ..........bbbb..........
        ........bbddddbb........
        .......bddbbbbddb.......
        ......bdbbddddbbdb......
        .....bdbbdbbbbdbbdb.....
        .....bdbdbddddbdbdb.....
        .....cdbbdbbbbdbbdc.....
        .....cbdbbddddbbdbc.....
        .....efbddbbbbddbce.....
        .....eeffbddddbccee.....
        .....eeeeffcccceee......
        .....ceeeeeeeeeeee......
        .....ceeeeeeeeeeee......
        .....feeeeeeeeeeee......
        .....cceeeeeeeeeee......
        ......feeeeeeeeeee......
        .....6fceeeeeeeeee6.....
        ....6776eeeeeeeee676....
        ...6777666eeee6666776...
        ..67768e67766777667776..
        ...668ee7768867788666...
        ......ee77eeee77ecee....
        ......ee6eeeeee6eef.....
        ......eeeeeeeeeeeef.....
        ......eeeeeeeeeeeef.....
        ......eeeeeeeeeeecf.....
        ......ceeeeeeeeeecf.....
        ......ceeeeeeeeeeff.....
        ......feeeeeeeeeefe.....
        .....6feeeeeeeeeef6.....
        ....6776eeeeeeeee676....
        ...6777666eeee6667776...
        ..6776ee67777777667776..
        ...668ee7768867788666...
        ......ee77eeee67ee......
        ......ee6eeeeee6ce......
        ......eefeeeeeeece......
        ......eeceeeeeeece......
        ......eeceeeeeeefe......
        ......eeceeeeeeefe......
        ......eeeeeeeeeefe......
        ......eeeeeeeeeece......
        .....6eeeeeeeeeece6.....
        ....6776eeeeeeeee676....
        ...6776666eeee6766776...
        ..6776ee77777777667776..
        ...668ce7768867788666...
        ......ce77eeee67ee......
        ......ce6eeeeee6ee......
        ......ceeeeeeeeeee......
        ......fcceeeeeecee......
        ......fccceeececce......
        ......fcceeecceccc......
        ......fccceecceccc......
        ......fccccceceecc......
        .....6fccccccccccf6.....
        ....6776ccccccccc676....
        ...6776676cccc6766776...
        ..6776cc77777777667776..
        ...668cc7768867788666...
        ......cc77cccc67cf......
        ......cc6cccccc6cf......
        `, SpriteKind.Food)
    mySprite.setPosition(randint(0, 100), randint(0, 100))
    panda.follow(mySprite)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    otherSprite.destroy(effects.spray, 500)
})
let mySprite: Sprite = null
let panda: Sprite = null
panda.setBounceOnWall(true)
panda = sprites.create(img`
    . f f f . . . . f f f . . . . . 
    f c c c f f f f c c c f . . . . 
    f c a d 1 1 1 1 d a c f . . . . 
    f a d 1 1 1 1 1 1 d f . . . . . 
    . f c c c 1 1 c c c d f . . . . 
    . f c f c 1 1 c f c d f f f . . 
    . f c c 1 c c 1 c c f d c c f . 
    . f d 1 1 f f 1 1 d f 1 1 c c f 
    . . f d d d d d d a c 1 1 1 c f 
    . . f c 1 1 1 1 1 c c 1 1 1 c f 
    . . f c 1 1 1 1 1 c c 1 1 1 c f 
    . . f c f f f f f c c 1 1 c c f 
    . . f c f . . . f c f f f f c f 
    . . f f . . . . f f . . . . f f 
    `, SpriteKind.Player)
panda.setVelocity(randint(20, 50), randint(40, 60))
